import sys 
import h5py
import os

sys.path.append(f'{os.getcwd()}/monitor/dwm3000')
from HDF5Storage import HDF5Storage


def merge_files():
    """
    Merge hdf5 files generated by different processes.
    """
    d_names = ["init.hdf5.tmp", "phone_report.hdf5.tmp"]
    d_struct = {} 
    for i in d_names:
        f = h5py.File(i,'r+')
        d_struct[i] = list(f.keys())
        f.close()

    os.system("rm -rf output.hdf5")
    for i in d_names:
        for j  in d_struct[i]:
            os.system('h5copy -i %s -o output.hdf5 -s %s -d %s' % (i, j, j))
    
    for i in d_names:
        os.system('rm -rf %s' % (i))

merge_files()
